export const STATIONS = [
  {
    id: 'S1',
    railName: ['Station 1:', 'Ratio Table'],
    title: 'Station A: Ratio Table',
    concept: 'Direct proportion & constant ratio (k = y ÷ x)',
    icon: '📋',
    cta: 'Test the Ratios 🔬',
    component: 'RatioTableLab',
  },
  {
    id: 'S2',
    railName: ['Station 2:', 'Graphs'],
    title: 'Station B: Graphs & Equations',
    concept: 'Straight lines through the origin (y = kx) & curves (y = k/x)',
    icon: '📈',
    cta: 'Plot the Points 📈',
    component: 'GraphPlotter',
  },
  {
    id: 'S3',
    railName: ['Station 3:', 'Inverse'],
    title: 'Station C: Inverse Proportion',
    concept: 'Constant product (x × y = k) & the area-rectangle model',
    icon: '👷',
    cta: 'Split the Work 👷',
    component: 'WorkerWorkshop',
  },
  {
    id: 'S4',
    railName: ['Station 4:', 'Detective'],
    title: 'Station D: Direct, Inverse or Neither?',
    concept: 'Master the Two Detective Tests: ÷ Test and × Test',
    icon: '🕵️',
    cta: 'Sort the Cards 🗂️',
    component: 'DetectiveDesk',
  },
  {
    id: 'S5',
    railName: ['Station 5:', 'Mission'],
    title: 'Station E: Solve It Like a Pro',
    concept: 'Multi-step mastery, unitary method & combined variation',
    icon: '🚀',
    cta: 'Launch Solution 🚀',
    component: 'MissionControl',
  },
];
